name: Deploy API Alpha

on:
  pull_request:
    branches: [dev]
    types: [closed]

jobs:
  if_merged:
  validate-alpha:
    name: Validate Prod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js 18.17.1
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.1'
          cache: 'npm'

      - name: Install dependencies
        run: npm clean-install

      - name: Prettier
        run: npm run lint:prettier
